version: 2

jobs:
  build:

    docker:
        - image: gcc:5.5

    steps:

      - checkout

      - run:
          name: checkout embedded-sht
          command: |
              git clone git@github.com:Sensirion/embedded-sht.git ../embedded-sht
              cd ../embedded-sht && make sht-common/sht_git_version.c && cd -
      - run:
          name: update common repo
          command: git submodule update --init
      - run: apt update
      - run: apt install -y zip
      - run:
          name: build drivers
          command: make && make clean
      - run:
          name: create and build release
          command: make release
